name: CI static site

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate structure
        run: |
          test -f index.html
      - name: Upload site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: |
            .
          if-no-files-found: error
          retention-days: 7
